### ISSUE TITLE
Coinbase loading problems

### ISSUE THREAD

**Issue by rapus95** [eprbell/dali-rp2#246] opened 2024-06-24 16:49 UTC
```
2024-06-24 18:04:21,675/dali/INFO: Reading crypto data using plugin 'dali.plugin.input.rest.coinbase'
2024-06-24 18:04:21,893/Coinbase/aaron/INFO: Error <Response [401]>: b'Unauthorized\n'
```
is what I get, when I take the API-keys from the legacy key there: https://www.coinbase.com/settings/api
![image](https://github.com/eprbell/dali-rp2/assets/5960902/fdbcb2f1-c1b4-41e9-9944-3d0bfd9196b5)

aswell as when I take the API-keys from there: https://portal.cdp.coinbase.com/access/api

Backstory: In the past, I was a 95% Coinbase Pro user and a 5% Coinbase user. But some time ago Coinbase Pro was somewhat removed. Now there's only an Advanced Mode in Coinbase. For the Coinbase Pro config I'm missing the API Key Passphrase. (Got only key and secret key). So I'm not sure how to import everything from Coinbase :/

**Comment by eprbell** [comment] 2024-06-24 17:38
The Coinbase plugin stopped working on 11/23, when Coinbase started deprecating endpoints the plugin was using: see #216.

**Comment by eprbell** [comment] 2024-06-26 03:07
Closing as duplicate of #216.

**Closed by eprbell** 2024-06-26 03:07 UTC
