### ISSUE TITLE
Issues with USDC->USD pair conversion

### ISSUE THREAD

**Issue by kevinkarnani** [eprbell/dali-rp2#112] opened 2023-01-24 07:20 UTC
Hey all,

Just wanted to show my appreciation for the creation of a tool like this! As a first time user of this tool, I had a few issues while attempting to use it. I have accounts on Coinbase + Coinbase Pro, so I got all the config info down before running into two issues. Initially, while not specifying a pair converter in the `.ini` file, I get the following logs (ran with the DEBUG prefix):

```
2023-01-24 02:07:12,667/CCXT-converter/high/DEBUG: Converting USDC to USD
2023-01-24 02:07:12,834/CCXT-converter/high/DEBUG: Using default exchange Binance.com type for Coinbase.
2023-01-24 02:07:12,986/dali/ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "~/miniforge3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 622, in fetch
    response.raise_for_status()
  File "~/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 451 Client Error:  for url: https://api.binance.com/api/v3/exchangeInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Desktop/crypto/dali-rp2/src/dali/dali_main.py", line 168, in _dali_main_internal
    resolved_transactions: List[AbstractTransaction] = resolve_transactions(transactions, dali_configuration, args.read_spot_price_from_web)
  File "~/Desktop/crypto/dali-rp2/src/dali/transaction_resolver.py", line 259, in resolve_transactions
    transaction = _update_spot_price_from_web(transaction, global_configuration)
  File "~/Desktop/crypto/dali-rp2/src/dali/transaction_resolver.py", line 136, in _update_spot_price_from_web
    conversion: RateAndPairConverter = _get_pair_conversion_rate(
  File "~/Desktop/crypto/dali-rp2/src/dali/transaction_resolver.py", line 108, in _get_pair_conversion_rate
    rate = cast(AbstractPairConverterPlugin, pair_converter).get_conversion_rate(timestamp, from_asset, to_asset, exchange)
  File "~/Desktop/crypto/dali-rp2/src/dali/abstract_pair_converter_plugin.py", line 129, in get_conversion_rate
    historical_bar = self.get_historic_bar_from_native_source(timestamp, from_asset, to_asset, exchange)
  File "~/Desktop/crypto/dali-rp2/src/dali/plugin/pair_converter/ccxt.py", line 220, in get_historic_bar_from_native_source
    for market in current_exchange.fetch_markets():
  File "~/miniforge3/lib/python3.9/site-packages/ccxt/binance.py", line 1614, in fetch_markets
    response = getattr(self, method)(query)
  File "~/miniforge3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)
  File "~/miniforge3/lib/python3.9/site-packages/ccxt/binance.py", line 6042, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "~/miniforge3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2802, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "~/miniforge3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 640, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "~/miniforge3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1742, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo 451  {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
```

Same issue with the historical converter when specified in the `.ini` file:
```
INFO: Country: us
INFO: Initialized input plugin 'dali.plugin.input.rest.coinbase Default Wallet'
INFO: Initialized input plugin 'dali.plugin.input.rest.coinbase_pro Default Wallet'
INFO: Initialized pair converter plugin 'dali.plugin.pair_converter.historic_crypto'
INFO: Reading crypto data using plugin 'dali.plugin.input.rest.coinbase Default Wallet'
INFO: Reading crypto data using plugin 'dali.plugin.input.rest.coinbase_pro Default Wallet'
INFO: Resolving transactions
ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "~Desktop/crypto/dali-rp2/src/dali/dali_main.py", line 168, in _dali_main_internal
    resolved_transactions: List[AbstractTransaction] = resolve_transactions(transactions, dali_configuration, args.read_spot_price_from_web)
  File "~/Desktop/crypto/dali-rp2/src/dali/transaction_resolver.py", line 259, in resolve_transactions
    transaction = _update_spot_price_from_web(transaction, global_configuration)
  File "~/Desktop/crypto/dali-rp2/src/dali/transaction_resolver.py", line 144, in _update_spot_price_from_web
    raise Exception(
Exception: Spot price for [hash]:[timestamp]:USDC->USD not found on any pair converter plugin
INFO: Log file: ./log/rp2_2023_01_24_01_47_46_468534.log
INFO: Generated output directory: output
INFO: Done
```

Its associated transaction:
```
2023-01-24 01:52:28,939/Coinbase/[name]/DEBUG: Transaction: {"id": "[hash]", "type": "interest", "status": "completed", "amount": {"amount": "0.001335", "currency": "USDC"}, "native_amount": {"amount": "0.00", "currency": "USD"}, "description": null, "created_at": "[timestamp]", "updated_at": "[timestamp]", "resource": "transaction", "resource_path": "[path]", "instant_exchange": false, "from": {"id": "[hash]", "resource": "user", "resource_path": "[path]", "currency": "USDC"}, "details": {"title": "USD Coin reward", "subtitle": "From Coinbase", "header": "Received 0.001335 USDC ($0.00)", "health": "positive"}, "hide_native_amount": false}
```

I'm wondering what the best alternative would be for the currency converter, since neither the default nor the historical work. If that information isn't present here, where could I find information like this? Also, please let me know if any more info is needed from me, especially if it is one of the "pseudo"-anonymized fields.

Thanks!

**Comment by macanudo527** [comment] 2023-01-24 12:56
The CCXT pair converter is probably a no-go for a while for US users as per issue #110 until we decide on a new default exchange.

The Historical Crypto plugin should work just fine since it uses Coinbase exclusively. @eprbell will have to answer this one. My guess is that there isn't a market for USDCUSD on Coinbase since they issue it right? So, it is always pegged 1:1 on that exchange. Is that right? Can you make a trade for USDC with USD on Coinbase? I'm not a user and I'm geo-locked out anyway.

**Comment by eprbell** [comment] 2023-01-24 17:20
Indeed unfortunately Coinbase doesn't have a USDCUSD market. So we need to fix #110 and add a Kraken pair converter.

**Comment by macanudo527** [comment] 2023-01-25 02:01
Or should we add logic for stable coins that are issued by an exchange and being held on that exchange to be 1:1?

I know you tend to go for the market price, and it would be hard to maintain, but just playing devil's advocate.

**Comment by eprbell** [comment] 2023-01-25 02:07
USDC is issued by Circle (Coinbase is a member, I think). I approve of devil's advocates 🙂, but I'd prefer not to special-case stable coins and to treat them like other coins: this makes the code cleaner and easier to maintain, as you said.

**Comment by kevinkarnani** [comment] 2023-02-09 06:21
Just saw the merge - gets me past the initial error! Very exciting. When I run the subsequent command, I get the following:

```
rp2_us -m fifo -o output/ -p rp2_ output/2022_crypto_data.ini output/2022_crypto_data.ods
INFO: Country: us
INFO: Generation Language: en
INFO: Accounting method: fifo
INFO: Configuration file: output/2022_crypto_data.ini
INFO: Input file: output/2022_crypto_data.ods
INFO: Processing 1INCH
WARNING: 1INCH InTransaction (2021-04-18 03:49:47+00:00, id 3): crypto_in * spot_price != fiat_in_no_fee: 196.000000 != 196.020000
# bunch more warnings and computations...
INFO: Processing BCH
ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "/Users/kevinkarnani/miniforge3/lib/python3.9/site-packages/rp2/ods_parser.py", line 257, in _process_constructor_argument_pack
    raise RP2RuntimeError(
rp2.rp2_error.RP2RuntimeError: Encountered an unresolved DaLI transaction (read DaLI's documentation / FAQ to learn how to resolve this issue): {'timestamp': '2021-02-03 00:31:56+0000', 'asset': 'BCH', 'from_exchange': 'Coinbase', 'from_holder': '[redacted]', 'to_exchange': '__unknown', 'to_holder': '__unknown', 'spot_price': Decimal('436.17876616377'), 'crypto_sent': Decimal('0.71204750000'), 'crypto_received': '__unknown', 'unique_id': '[redacted]', 'notes': None, 'internal_id': 10}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/miniforge3/lib/python3.9/site-packages/rp2/rp2_main.py", line 143, in _rp2_main_internal
    input_data: InputData = parse_ods(configuration=configuration, asset=asset, input_file_handle=input_file_handle)
  File "~/miniforge3/lib/python3.9/site-packages/rp2/ods_parser.py", line 128, in parse_ods
    _create_and_process_transaction(
  File "~/miniforge3/lib/python3.9/site-packages/rp2/ods_parser.py", line 168, in _create_and_process_transaction
    transaction: AbstractTransaction = _create_transaction(configuration, current_table_type, internal_id, row_values)
  File "~/miniforge3/lib/python3.9/site-packages/rp2/ods_parser.py", line 291, in _create_transaction
    argument_pack = _process_constructor_argument_pack(configuration, argument_pack, internal_id, "IntraTransaction")
  File "~/miniforge3/lib/python3.9/site-packages/rp2/ods_parser.py", line 267, in _process_constructor_argument_pack
    raise RP2ValueError(f"Argument '{numeric_parameter}' has non-numeric value: {value}") from exc
rp2.rp2_error.RP2ValueError: Argument 'crypto_received' has non-numeric value: __unknown
```

This was without specifying a pair converter. When specify Kraken specifically, I get the following:

```
❯ dali_us -s -o output -p 2022_ dali_input/test_config.ini
INFO: Country: us
INFO: Initialized input plugin 'dali.plugin.input.rest.coinbase Default Wallet'
INFO: Initialized input plugin 'dali.plugin.input.rest.coinbase_pro Default Wallet'
ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "~/miniforge3/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "~/miniforge3/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "~/miniforge3/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'exchange_locked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/miniforge3/lib/python3.9/site-packages/dali/dali_main.py", line 124, in _dali_main_internal
    plugin_configuration = _validate_plugin_configuration(ini_config, section_name, signature(plugin_module.PairConverterPlugin))
  File "~/miniforge3/lib/python3.9/site-packages/dali/dali_main.py", line 407, in _validate_plugin_configuration
    result[parameter] = ini_config.getboolean(plugin_name, parameter)
  File "~/miniforge3/lib/python3.9/configparser.py", line 828, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "~/miniforge3/lib/python3.9/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "~/miniforge3/lib/python3.9/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "~/miniforge3/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'exchange_locked' in section: 'dali.plugin.pair_converter.ccxt'
INFO: Log file: ./log/rp2_2023_02_09_01_16_19_197732.log
INFO: Generated output directory: output
INFO: Done
```

this is the setup of the config:

```
[dali.plugin.pair_converter.ccxt]
historical_price_type = nearest
default_exchange = Kraken
google_api_key = [redacted]
```

any thoughts? I thought I followed the updated docs pretty well, or maybe I jumped the gun without waiting for your responses haha.

**Comment by macanudo527** [comment] 2023-02-09 07:33
Try explicitly declaring `exchange_locked`:
```
[dali.plugin.pair_converter.ccxt]
historical_price_type = nearest
default_exchange = Kraken
google_api_key = [redacted]
exchange_locked = False
```
By the way, the new default exchange is Kraken, so declaring it is now redundant. Or at least, should be. :)

**Comment by macanudo527** [comment] 2023-02-09 07:44
@kevinkarnani I submitted a #118 to resolve this. However, it looks like you are missing some key information from your BCH transaction. It looks like you are missing `crypto_received` from a transaction. Is this from a CSV? or from the REST plugin? Do you usually use BCH for transfers and you are missing a corresponding transaction from the receiving exchange/wallet?

**Comment by kevinkarnani** [comment] 2023-02-09 17:00
I wanted to do a manual test just to see if explicitly declaring it would give the same result, which it didn't. I didn't see anything in the docs about it, but I tried your change, and here is what I got:

```
INFO: Resolving transactions
ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "~miniforge3/lib/python3.9/site-packages/dali/dali_main.py", line 168, in _dali_main_internal
    resolved_transactions: List[AbstractTransaction] = resolve_transactions(transactions, dali_configuration, args.read_spot_price_from_web)
  File "~/miniforge3/lib/python3.9/site-packages/dali/transaction_resolver.py", line 263, in resolve_transactions
    transaction = _update_spot_price_from_web(transaction, global_configuration)
  File "~/miniforge3/lib/python3.9/site-packages/dali/transaction_resolver.py", line 136, in _update_spot_price_from_web
    conversion: RateAndPairConverter = _get_pair_conversion_rate(
  File "~/miniforge3/lib/python3.9/site-packages/dali/transaction_resolver.py", line 108, in _get_pair_conversion_rate
    rate = cast(AbstractPairConverterPlugin, pair_converter).get_conversion_rate(timestamp, from_asset, to_asset, exchange)
  File "~/miniforge3/lib/python3.9/site-packages/dali/abstract_pair_converter_plugin.py", line 130, in get_conversion_rate
    historical_bar = self.get_historic_bar_from_native_source(timestamp, from_asset, to_asset, exchange)
  File "~/miniforge3/lib/python3.9/site-packages/dali/plugin/pair_converter/ccxt.py", line 261, in get_historic_bar_from_native_source
    result = self.find_historical_bar(from_asset, to_asset, timestamp, exchange)
  File "~/miniforge3/lib/python3.9/site-packages/dali/plugin/pair_converter/ccxt.py", line 357, in find_historical_bar
    csv_bars: Dict[datetime, HistoricalBar] = csv_reader.get_historical_bars_for_pair(from_asset, to_asset)
  File "~/miniforge3/lib/python3.9/site-packages/dali/plugin/pair_converter/csv/kraken.py", line 97, in get_historical_bars_for_pair
    with ZipFile(BytesIO(self._google_file_to_bytes(base_file))) as zipped_ohlcvt:
  File "~/miniforge3/lib/python3.9/site-packages/dali/plugin/pair_converter/csv/kraken.py", line 188, in _google_file_to_bytes
    file_response: Response = self.__session.get(f"{_GOOGLE_APIS_URL}/{data[_FILES][0][_ID]}", params=params, timeout=self.__TIMEOUT)
KeyError: 'files'
```

As for the other error, the only 2 sources of data I have are my Coinbase and Coinbase Pro wallets, both of which were configured using the REST API. I don't do anything fancy with them, ive only bought, sold, and transferred between coinbase and coinbase pro (and vice versa).

**Comment by macanudo527** [comment] 2023-02-10 15:07
You didn't by any chance run this with `LOG_LEVEL=DEBUG` did you? That would help out a lot. It appears a file is missing from the Google Drive. To run with debug log level you can just prepend the `dali_us` command with `LOG_LEVEL=DEBUG`:
```
LOG_LEVEL=DEBUG bin/dali_us -s -o output/ config/test_config.ini
```
There should be a line that looks like this:
```
2023-02-10 23:47:36,934/Kraken.com_CSVOHLCVT/DEBUG: Attempting to load USDT_OHLCVT.zip
```

**Comment by macanudo527** [comment] 2023-02-11 00:21
I just noticed @kevinkarnani that your first error -
`rp2.rp2_error.RP2ValueError: Argument 'crypto_received' has non-numeric value: __unknown`
 is coming from rp2 and not Dali. Were you able to get prices resolved with the historical plugin with Dali?

**Comment by kevinkarnani** [comment] 2023-02-11 04:25
Interesting, i get the files keyword error because somehow my google API token, which I just made for this, is invalid. Here is the error for future reference:

```
2023-02-10 23:09:55,440/Kraken.com_CSVOHLCVT/DEBUG: Attempting to load SOL_OHLCVT.zip
2023-02-10 23:09:55,531/Kraken.com_CSVOHLCVT/DEBUG: Retrieved {'error': {'code': 400, 'message': 'API key not valid. Please pass a valid API key.', 'errors': [{'message': 'API key not valid. Please pass a valid API key.', 'domain': 'global', 'reason': 'badRequest'}], 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'drive.googleapis.com'}}]}} from https://www.googleapis.com/drive/v3/files?q=[key]
2023-02-10 23:09:55,531/dali/ERROR: Fatal exception occurred:
Traceback (most recent call last):
```
When I uncomment the pair converter in the config file and try again, at least the .ods file is successfully generated by dali, but then the error shows up in rp2 afterwards. Check this out as an example:

```
2023-02-10 23:20:26,285/dali/DEBUG: Unresolvable transaction (no unique_id): IntraTransaction:
  plugin=Coinbase
  unique_id=__unknown
  raw_data={"id": "[redacted]", "type": "send", "status": "completed", "amount": {"amount": "-0.00178050", "currency": "BTC"}, "native_amount": {"amount": "-70.15", "currency": "USD"}, "description": "[redacted]", "created_at": "2021-02-06T01:36:29Z", "updated_at": "2021-11-04T21:28:24Z", "resource": "transaction", "resource_path": "/v2/accounts/[redacted]/transactions/[redacted]", "instant_exchange": false, "off_chain_status": "completed", "network": {"status": "off_blockchain", "status_description": null}, "to": {"resource": "bitcoin_address", "address": "[redacted]", "currency": "BTC", "address_info": {"address": "[redacted]"}, "address_url": "https://blockchain.info/address/[redacted]"}, "idem": "[redacted]", "details": {"title": "Sent Bitcoin", "subtitle": "To Bitcoin address", "header": "Sent 0.0017805 BTC ($70.15)", "health": "positive"}, "hide_native_amount": false}
  timestamp=2021-02-06 01:36:29+0000
  asset=BTC
  from_exchange=Coinbase
  from_holder=[redacted]
  to_exchange=__unknown
  to_holder=__unknown
  spot_price=39399
  crypto_sent=0.00178050
  crypto_received=__unknown
  notes=None
```

**Comment by eprbell** [comment] 2023-02-11 05:23
> Interesting, i get the files keyword error because somehow my google API token, which I just made for this, is invalid. Here is the error for future reference:
> 
> ```
> 2023-02-10 23:09:55,440/Kraken.com_CSVOHLCVT/DEBUG: Attempting to load SOL_OHLCVT.zip
> 2023-02-10 23:09:55,531/Kraken.com_CSVOHLCVT/DEBUG: Retrieved {'error': {'code': 400, 'message': 'API key not valid. Please pass a valid API key.', 'errors': [{'message': 'API key not valid. Please pass a valid API key.', 'domain': 'global', 'reason': 'badRequest'}], 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'drive.googleapis.com'}}]}} from https://www.googleapis.com/drive/v3/files?q=[key]
> 2023-02-10 23:09:55,531/dali/ERROR: Fatal exception occurred:
> Traceback (most recent call last):
> ```

This is interesting info. @macanudo527, we should use `log.info` with this message instead of `log.debug`, so that it appears also in the regular log, not just in the debug one.

> When I uncomment the pair converter in the config file and try again, at least the .ods file is successfully generated by dali, but then the error shows up in rp2 afterwards. Check this out as an example:
> 
> ```
> 2023-02-10 23:20:26,285/dali/DEBUG: Unresolvable transaction (no unique_id): IntraTransaction:
>   plugin=Coinbase
>   unique_id=__unknown
>   raw_data={"id": "[redacted]", "type": "send", "status": "completed", "amount": {"amount": "-0.00178050", "currency": "BTC"}, "native_amount": {"amount": "-70.15", "currency": "USD"}, "description": "[redacted]", "created_at": "2021-02-06T01:36:29Z", "updated_at": "2021-11-04T21:28:24Z", "resource": "transaction", "resource_path": "/v2/accounts/[redacted]/transactions/[redacted]", "instant_exchange": false, "off_chain_status": "completed", "network": {"status": "off_blockchain", "status_description": null}, "to": {"resource": "bitcoin_address", "address": "[redacted]", "currency": "BTC", "address_info": {"address": "[redacted]"}, "address_url": "https://blockchain.info/address/[redacted]"}, "idem": "[redacted]", "details": {"title": "Sent Bitcoin", "subtitle": "To Bitcoin address", "header": "Sent 0.0017805 BTC ($70.15)", "health": "positive"}, "hide_native_amount": false}
>   timestamp=2021-02-06 01:36:29+0000
>   asset=BTC
>   from_exchange=Coinbase
>   from_holder=[redacted]
>   to_exchange=__unknown
>   to_holder=__unknown
>   spot_price=39399
>   crypto_sent=0.00178050
>   crypto_received=__unknown
>   notes=None
> ```

This occurs because you sent BTC from Coinbase to an external address and DaLI doesn't know what this address is: can you clarify if it is a wallet or another exchange? Since DaLI doesn't have recipient information it fills the `to` fields with `__unknown`, but you can provide this missing information: see [this FAQ](https://github.com/eprbell/dali-rp2/blob/main/docs/user_faq.md#what-if-a-transaction-is-generated-with-some-fields-set-to-__unknown) for more details on transaction resolution. In particular be sure to read the [manual plugin](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#partial-transactions-and-transaction-resolution) section of the documentation, which contains examples and explanations on how to add the missing half of an unresolved transaction.

**Comment by kevinkarnani** [comment] 2023-02-11 06:21
hm - so i think coinbase has this thing where if you send to another coinbase user via username or email, the details dont get filled... very weird. When I look at my transaction history in Coinbase, i see the following:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/17555718/218243702-53c6774d-bbbd-48b5-be88-f491fbd310cc.png">

However, when i look at a software i paid for in 2021 that kept track of this (CoinTracker.io), I see more details:

![image](https://user-images.githubusercontent.com/17555718/218243757-ae91f8c5-4300-4953-8339-ba61e2aa6300.png)

A normal example would be something like this:

![image](https://user-images.githubusercontent.com/17555718/218243856-f771aa80-cfb9-4bbb-990d-7d6f6ebedc70.png)

Is there anything specific this software is doing that cannot be emulated on this side? the setup is exactly the same (API key)
with the exact same perms, so I assume the Coinbase internal API must be yielding this information somewhere.

**Comment by eprbell** [comment] 2023-02-11 06:43
The DaLI Coinbase plugin does capture [sending coins to another Coinbase user](https://github.com/eprbell/dali-rp2/blob/main/src/dali/plugin/input/rest/coinbase.py#L546). I can't speak to what closed source software is doing, but your transaction data doesn't seem to match the logic from the DaLI code I linked and it also says explicitly: `"title": "Sent Bitcoin", "subtitle": "To Bitcoin address"`, so it falls in the [general send case](https://github.com/eprbell/dali-rp2/blob/main/src/dali/plugin/input/rest/coinbase.py#L595). Are you positive this transaction is to another Coinbase user? Did you send the coins to them using their Coinbase wallet address (instead of their email)? Could it be that you sent the funds to an external account (a wallet maybe)?

**Comment by kevinkarnani** [comment] 2023-02-11 07:25
How odd and frustrating, using multiple softwares to remember what I did 2 years ago because I don't remember and Coinbase didn't want to use the same format as the other txns. This is what im used to seeing:

![image0](https://user-images.githubusercontent.com/17555718/218246014-d3cebde2-2290-4f36-abcc-d71cfb819870.jpeg)

I went and downloaded the Coinbase all time csv, and that row specifically has this:

2021-02-06T01:36:29Z | Send | BTC | 0.0017805 | USD | 39400.00 |   |   |   | Sent 0.0017805 BTC to [redacted]
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

So your suspicions were correct, which makes sense for everything except why Coinbase wouldn't be more clear lol. Anyways, thank you for all this! I will try these changes sometime tomorrow morning.

**Comment by macanudo527** [comment] 2023-02-11 07:40
@kevinkarnani I've confirmed that the reason you are getting that `KeyError` for `files` is that you have an invalid Google API key (i.e. Google doesn't recognize it as a key for anything). I tested my setup with a bogus key and got the exact same error. A added a commit that now handles that and gives a more user friendly error.

Note that if it was an unauthorized key (ie. you didn't authorize the use of Google Drive, which you have to do explicitly, it would be a different error.)

If you do still want to use the CCXT pair converter plugin, you will have to get a valid key. Did you follow the instructions from the [configuration screen readme](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#ccxt)?

**Comment by macanudo527** [comment] 2023-03-07 02:03
@kevinkarnani Were you able to resolve this issue?

**Comment by eprbell** [comment] 2023-04-02 01:18
I think it's ok to close this. If there are still more questions we can reopen.

**Closed** 2023-04-02 23:46 UTC
